config/routes.rb
Rails.application.routes.draw do
  resources :properties
  post 'properties/:id/statuses', to: "properties#update_status", as: "update_property_status"
  get 'properties/:id/comments', to: "properties#comments", as: "get_property_comments"
  get 'properties/:id/comments/new', to: "properties#new_comment", as: "new_property_comment"
  post 'properties/:id/comments', to: "properties#create_comment", as: "create_property_comments"
  get 'properties/:id/history_items', to: "properties#history_items", as: "get_property_history_items"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'properties#index'
  resources 'dashboards', only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  include RecordHistoryConcern

  validates_presence_of :title, :body, :user, :property
  belongs_to :user
  belongs_to :property

  private

  def history_item_summary
    "#{user.email} commented: #{body}."
  end

end

app/models/concerns/record_history_concern.rb
module RecordHistoryConcern
  extend ActiveSupport::Concern

  def self.included(base)
    base.class_eval do
      has_many :history_items, as: :historicizable
      after_save :create_history_item
    end
  end

  def create_history_item
    self.property.history_items.create(historicizable: self, summary: self.history_item_summary)
  end

  def history_item_summary
    raise NotImplementedError
  end

end

app/models/history_item.rb
class HistoryItem < ApplicationRecord
  belongs_to :historicizable, polymorphic: true
  belongs_to :property#historicizable: meaning an event which can or should be recordable in history
end

app/models/property.rb
class Property < ApplicationRecord
  validates_presence_of :title, :address_line1, :city, :zip
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :history_items, dependent: :destroy
  has_many :status_updates, dependent: :destroy

  after_create :create_default_status

  def current_status
    status_updates.last
  end

  def display_address
    "#{address_line1}, #{city}"
  end

  private
  def create_default_status
    self.status_updates.create(user_id: user.id, status: :listed)
  end
end

app/models/status_update.rb
class StatusUpdate < ApplicationRecord
  include RecordHistoryConcern

  enum status: [:listed, :viewing, :financing, :payment, :sold]

  belongs_to :property
  belongs_to :user


  private

  def history_item_summary
    "#{user.email} changed status to: #{status}."
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[ show edit update destroy comments new_comment create_comment history_items update_status]

  # GET /properties or /properties.json
  def index
    @properties = Property.includes(:comments).order(:created_at).last(10)
  end

  # GET /properties/1 or /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties or /properties.json
  def create
    @property = Property.new(property_params)
    @property.user = current_user

    respond_to do |format|
      if @property.save
        format.html { redirect_to property_url(@property), notice: "Property was successfully created." }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1 or /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to property_url(@property), notice: "Property was successfully updated." }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1 or /properties/1.json
  def destroy
    @property.destroy

    respond_to do |format|
      format.html { redirect_to properties_url, notice: "Property was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def comments
    @comments = @property.comments.order(created_at: :desc)
  end

  def new_comment
    @comment = @property.comments.new
  end

  def create_comment
    @property.comments.create(user: current_user, title: comments_params[:title], body: comments_params[:body])
    redirect_to get_property_comments_url(@property)
  end

  def history_items
    @history_items = @property.history_items.order(created_at: :desc)
  end

  def update_status
    @property.status_updates.create(user: current_user, status: status_params[:status].to_i)
    redirect_to get_property_history_items_url(@property), notice: "Property Status was successfully updated."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_property
    @property = Property.find(params[:id])
    @current_status = @property.current_status
  end

  # Only allow a list of trusted parameters through.
  def property_params
    params.require(:property).permit(:title, :address_line1, :address_line2, :city, :zip, :description, :picture_url, :status)
  end

  def comments_params
    params.permit(:title, :body)
  end

  def status_params
    params.permit(:status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <a href="#" class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
    <div class="d-flex gap-2 w-100 justify-content-between">
      <div>
        <h6 class="mb-0"><%= comment.title %></h6>
        <p class="mb-0 opacity-75"><%= comment.body %></p>
        <p class="mb-0 opacity-75">by: <%= comment.user.email %></p>
      </div>
      <small class="opacity-50 text-nowrap"><%= time_ago_in_words comment.created_at %></small>
    </div>
  </a>
</div>

app/views/comments/_form.html.erb
<%= form_with(url: create_property_comments_path, method: "post") do |form| %>
  <%= form.hidden_field :property_id, value: property.id %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<div>
  <%= link_to "Back to property", get_property_comments_path(@property) %>
</div>

app/views/dashboards/index.html.erb
<div class="container dashboard-container">
  <div class="row">
    <div class="col-md-4">
      <div class="my-3 p-3 bg-body rounded shadow-sm">
        <h6 class="border-bottom pb-2 mb-0">My Projects</h6>
        <div class="d-flex text-muted pt-3">
          <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false">
            <title>Placeholder</title>
            <rect width="100%" height="100%" fill="#007bff"/>
            <text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text>
          </svg>
          <p class="pb-3 mb-0 small lh-sm border-bottom">
            <strong class="d-block text-gray-dark">@username</strong>
            Some representative placeholder content, with some information about this user. Imagine this being some sort
            of status update, perhaps?
          </p>
        </div>
        <div class="d-flex text-muted pt-3">
          <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false">
            <title>Placeholder</title>
            <rect width="100%" height="100%" fill="#e83e8c"/>
            <text x="50%" y="50%" fill="#e83e8c" dy=".3em">32x32</text>
          </svg>
          <p class="pb-3 mb-0 small lh-sm border-bottom">
            <strong class="d-block text-gray-dark">@username</strong>
            Some more representative placeholder content, related to this other user. Another status update, perhaps.
          </p>
        </div>
        <div class="d-flex text-muted pt-3">
          <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false">
            <title>Placeholder</title>
            <rect width="100%" height="100%" fill="#6f42c1"/>
            <text x="50%" y="50%" fill="#6f42c1" dy=".3em">32x32</text>
          </svg>
          <p class="pb-3 mb-0 small lh-sm border-bottom">
            <strong class="d-block text-gray-dark">@username</strong>
            This user also gets some representative placeholder content. Maybe they did something interesting, and you
            really want to highlight this in the recent updates.
          </p>
        </div>
        <small class="d-block text-end mt-3">
          <a href="#">View All</a>
        </small>
      </div>
    </div>
    <div class="col-md-4">
      <div class="my-3 p-3 bg-body rounded shadow-sm">
        <h6 class="border-bottom pb-2 mb-0">By Activities</h6>
        <div class="d-flex text-muted pt-3">
          <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false">
            <title>Placeholder</title>
            <rect width="100%" height="100%" fill="#007bff"/>
            <text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text>
          </svg>
          <p class="pb-3 mb-0 small lh-sm border-bottom">
            <strong class="d-block text-gray-dark">@username</strong>
            Some representative placeholder content, with some information about this user. Imagine this being some sort
            of status update, perhaps?
          </p>
        </div>
        <div class="d-flex text-muted pt-3">
          <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false">
            <title>Placeholder</title>
            <rect width="100%" height="100%" fill="#e83e8c"/>
            <text x="50%" y="50%" fill="#e83e8c" dy=".3em">32x32</text>
          </svg>
          <p class="pb-3 mb-0 small lh-sm border-bottom">
            <strong class="d-block text-gray-dark">@username</strong>
            Some more representative placeholder content, related to this other user. Another status update, perhaps.
          </p>
        </div>
        <div class="d-flex text-muted pt-3">
          <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false">
            <title>Placeholder</title>
            <rect width="100%" height="100%" fill="#6f42c1"/>
            <text x="50%" y="50%" fill="#6f42c1" dy=".3em">32x32</text>
          </svg>
          <p class="pb-3 mb-0 small lh-sm border-bottom">
            <strong class="d-block text-gray-dark">@username</strong>
            This user also gets some representative placeholder content. Maybe they did something interesting, and you
            really want to highlight this in the recent updates.
          </p>
        </div>
        <small class="d-block text-end mt-3">
          <a href="#">View All</a>
        </small>
      </div>
    </div>

    <div class="col-md-4">
      <div class="my-3 p-3 bg-body rounded shadow-sm">
        <h6 class="border-bottom pb-2 mb-0">New Projects</h6>
        <div class="d-flex text-muted pt-3">
          <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false">
            <title>Placeholder</title>
            <rect width="100%" height="100%" fill="#007bff"/>
            <text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text>
          </svg>
          <p class="pb-3 mb-0 small lh-sm border-bottom">
            <strong class="d-block text-gray-dark">@username</strong>
            Some representative placeholder content, with some information about this user. Imagine this being some sort
            of status update, perhaps?
          </p>
        </div>
        <div class="d-flex text-muted pt-3">
          <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false">
            <title>Placeholder</title>
            <rect width="100%" height="100%" fill="#e83e8c"/>
            <text x="50%" y="50%" fill="#e83e8c" dy=".3em">32x32</text>
          </svg>
          <p class="pb-3 mb-0 small lh-sm border-bottom">
            <strong class="d-block text-gray-dark">@username</strong>
            Some more representative placeholder content, related to this other user. Another status update, perhaps.
          </p>
        </div>
        <div class="d-flex text-muted pt-3">
          <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false">
            <title>Placeholder</title>
            <rect width="100%" height="100%" fill="#6f42c1"/>
            <text x="50%" y="50%" fill="#6f42c1" dy=".3em">32x32</text>
          </svg>
          <p class="pb-3 mb-0 small lh-sm border-bottom">
            <strong class="d-block text-gray-dark">@username</strong>
            This user also gets some representative placeholder content. Maybe they did something interesting, and you
            really want to highlight this in the recent updates.
          </p>
        </div>
        <small class="d-block text-end mt-3">
          <a href="#">View All</a>
        </small>
      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EstateGlee</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>

<body>
<div class="container py-3">
  <header>
    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img">
          <title>EstateGlee</title>
          <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path>
        </svg>
        <span class="fs-4">EstateGlee</span>
      </a>
      <% if current_user %>
        <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
          <a class="me-3 py-2 text-dark text-decoration-none" href="#">Dashboard</a>
          <%= link_to 'All Properties', properties_path, class: "me-3 py-2 text-dark text-decoration-none" %>
          <a class="me-3 py-2 text-dark text-decoration-none" href="#">Profile</a>
          <%= link_to "Log out", destroy_user_session_path, { :method => :delete, :class => "me-3 py-2 text-dark text-decoration-none" } %>
        </nav>
      <% end %>
    </div>
  </header>
</div>
<main>
  <div class="container py-3">
    <%= yield %>
  </div>
</main>
</body>
</html>

app/views/properties/_form.html.erb
<%= form_with(model: property) do |form| %>
  <% if property.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
        <% property.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :address_line1, style: "display: block" %>
    <%= form.text_field :address_line1 %>
  </div>

  <div>
    <%= form.label :address_line2, style: "display: block" %>
    <%= form.text_field :address_line2 %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :zip, style: "display: block" %>
    <%= form.text_field :zip %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :picture_url, style: "display: block" %>
    <%= form.text_field :picture_url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/properties/_history_item.html.erb
<div id="<%= dom_id history_item %>">
  <a href="#" class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
    <div class="d-flex gap-2 w-100 justify-content-between">
      <div>
        <h6 class="mb-0"><%= history_item.summary %></h6>
      </div>
      <small class="opacity-50 text-nowrap"><%= time_ago_in_words history_item.created_at %></small>
    </div>
  </a>
</div>

app/views/properties/_property.html.erb
<div id="<%= dom_id property %>">
  <div class="p-5 mb-4 bg-light rounded-3">
    <%= link_to "Edit", edit_property_path(@property) %>
    <div class="container-fluid py-5">
      <h1 class="display-5 fw-bold"><%= @property.title %></h1>
      <h3 class="fw-bold"><%= @property.display_address %></h3>
      <p class="col-md-8 fs-4"><%= @property.description %></p>
      <p class="col-md-8 fs-4 fw-bold">Current Status: <%= @current_status.status %></p>
      <div class="row col-md-8 mb-2 input-group">
        <%= form_with(url: update_property_status_path, method: "post") do |form| %>
          <%= form.hidden_field :property_id, value: property.id %>
          <div class="col-md-3 mb-2"><%= form.select :status, StatusUpdate.statuses, { selected: StatusUpdate.statuses[@current_status.status] }, { :class => 'form-select' } %></div>
          <div class="col-md-3"><%= form.submit "Update", { :class => 'btn btn-outline-secondary' } %></div>
        <% end %>
      </div>

      <div class="container">
        <div class="row">
          <div class="col-6 ps-0 col-md-2 h-5"> <%= link_to "View Comments", get_property_comments_path(@property) %></div>
          <div class="col-6 ps-0 col-md-2 h-5"> <%= link_to "View History", get_property_history_items_path(@property) %></div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/properties/_property_list_item.html.erb
<div class="row list-item-container border-bottom">
  <%= link_to property_url(property) do %>
    <div class="row property-title">
      <p class="fs-4"><%= property.title %></p>
    </div>
  <% end %>
  <div class="row">
    <p class="fs-5"><%= property.display_address %></p>
  </div>
  <div class="row">
    <p class="fs-5">Status: <%= property.current_status.status %></p>
  </div>
  <div class="row">
    <p class="fs-5">Comments: <%= property.comments.count.positive? ? (link_to property.comments.count, get_property_comments_path(property)) : '0' %> </p>
  </div>
</div>

app/views/properties/comments.html.erb
<p style="color: green"><%= notice %></p>

<%= render @property %>
<div class="row g-5">
  <div class="col-md-6 justify-content-between">
    <h2>Comments</h2>
    <%= link_to "Add a comment", new_property_comment_path(@property) %>
  </div>
</div>

<div class="list-group w-auto">
  <% @comments.each do |comment| %>
    <%= render comment %>
  <% end %>
</div>

app/views/properties/edit.html.erb
<h1>Editing property</h1>

<%= render "form", property: @property %>

<br>

<div>
  <%= link_to "Show this property", @property %> |
  <%= button_to "Destroy this property", @property, method: :delete %>
  <%= link_to "Back to properties", properties_path %>
</div>

app/views/properties/history_items.html.erb
<p style="color: green"><%= notice %></p>

<%= render @property %>
<div class="row g-5">
  <div class="col-md-6 justify-content-between">
    <h2>History Items</h2>
  </div>
</div>

<div class="list-group w-auto">
  <% @history_items.each do |history_item| %>
    <%= render partial: 'history_item', locals: { history_item: history_item } %>
  <% end %>
</div>

app/views/properties/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="my-3 p-3 bg-body rounded shadow-sm">
        <h6 class="border-bottom pb-2 mb-0">My Properties</h6>
        <% @properties.each do |property| %>
          <%= render 'property_list_item', property: property %>
        <% end %>
      </div>
      <nav aria-label="Page navigation example">
        <ul class="pagination">
          <li class="page-item"><a class="page-link" href="#">Previous</a></li>
          <li class="page-item"><a class="page-link" href="#">1</a></li>
          <li class="page-item"><a class="page-link" href="#">2</a></li>
          <li class="page-item"><a class="page-link" href="#">3</a></li>
          <li class="page-item"><a class="page-link" href="#">Next</a></li>
        </ul>
      </nav>
    </div>
  </div>
</div>

<%= link_to "New property", new_property_path %>

app/views/properties/new.html.erb
<h1>New property</h1>

<%= render "form", property: @property %>

<br>

<div>
  <%= link_to "Back to properties", properties_path %>
</div>

app/views/properties/new_comment.html.erb
<%= render partial: "comments/form", locals: { comment: @comment, property: @property } %>

app/views/properties/show.html.erb
<p style="color: green"><%= notice %></p>
<div>
  <%= link_to "Back to properties", properties_path %>
</div>

<%= render @property %>